# Generated by Django 4.0.3 on 2022-03-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
