# Generated by Django 4.0.3 on 2022-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_rename_name_pep_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='pep',
        ),
    ]
