# Generated by Django 4.0.3 on 2022-03-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_alter_experience_pep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='pep',
            new_name='title',
        ),
    ]
