# Generated by Django 4.0.3 on 2022-03-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_rename_pep_experience_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('producers', models.ManyToManyField(related_name='producers', to='rest_api.producer')),
            ],
        ),
        migrations.AddField(
            model_name='producer',
            name='productions',
            field=models.ManyToManyField(related_name='productions', to='rest_api.production'),
        ),
    ]
