# Generated by Django 4.0.3 on 2022-03-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_producer_production_producer_productions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='productions',
            field=models.ManyToManyField(blank=True, related_name='productions', to='rest_api.production'),
        ),
        migrations.AlterField(
            model_name='production',
            name='producers',
            field=models.ManyToManyField(blank=True, default='Unknown', related_name='producers', to='rest_api.producer'),
        ),
    ]
