# Generated by Django 4.0.3 on 2022-03-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField(max_length=1000)),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('condition', models.CharField(choices=[('0', 'Ough'), ('1', 'Very bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Not so bad'), ('5', 'Like new')], default='3', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.genre')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.year')),
            ],
        ),
    ]
