# Generated by Django 4.0.3 on 2022-03-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': ' Экземпляр книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='books',
            name='condition',
            field=models.CharField(choices=[('Ough', '0'), ('Very bad', '1'), ('Bad', '2'), ('Normal', '3'), ('Not so bad', '4'), ('Like new', '5')], default='3', max_length=20),
        ),
    ]
