# Generated by Django 4.0.3 on 2022-03-09 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_author_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c2bde3a6-daef-4bcb-bfc7-cfb398cf6247'), help_text='Уникальный ID для этого экземпляра книги из целой библиотеки', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.books')),
            ],
        ),
    ]
