# Generated by Django 4.0.3 on 2022-03-14 23:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('65663137-557f-409b-958f-e618cc423ebd'), help_text='Уникальный ID для этого экземпляра книги из целой библиотеки', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
