# Generated by Django 4.0.3 on 2022-03-14 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_bookinstance_id_alter_books_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='quantitty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e23385d1-b477-46d7-85bd-7a35317a7ec3'), help_text='Уникальный ID для этого экземпляра книги из целой библиотеки', primary_key=True, serialize=False),
        ),
    ]
